services:                              # Секция описания сервисов (контейнеров)
  app:                                 # Имя сервиса для внутренней сети Docker
    build: .                           # Сборка образа из Dockerfile в этой папке
    container_name: app                # Фиксированное имя контейнера в системе
    restart: always                    # Автоперезапуск при падении или перезагрузке
    ports:                             # Проброс портов
      - "8000:8000"                    # Внешний порт 8000 -> Внутренний порт 8000
